version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: inheritance-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - inheritance-network

    nginx:
        image: nginx:stable
        container_name: inheritance-nginx
        restart: unless-stopped
        ports:
            - "8008:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - inheritance-network

    mysql:
        image: mysql:8.0
        container_name: inheritance-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-inheritance}
            MYSQL_USER: ${DB_USERNAME:-inheritance}
            MYSQL_PASSWORD: ${DB_PASSWORD:-inheritance}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-inheritance}
        ports:
            - "3308:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - inheritance-network

volumes:
    mysql-data:

networks:
    inheritance-network:
        driver: bridge
